title: mash
email: mash@yree.io
description: >
  as simple as potatoes!
  a minimalist web stack that combines the power of maud, axum, sqlx and htmx.

url: https://yree.io
baseurl: /mash
git_repo: yree/mash

remote_theme: yree/mold
